version: "3.7"

networks:
  loki:

services:
  app_python:
      image: rkbekzat/moscow_time:latest
      container_name: app_python
      ports:
        - "8080:8080"
      logging: &logging
        driver: "json-file"
        options:
          tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
      networks:
        - loki

  app_go:
    image: rkbekzat/weather:latest
    container_name: app_go
    ports:
      - "8081:8081"
    logging: *logging
    networks:
      - loki


  loki:
    container_name: loki
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *logging
    networks:
      - loki


  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    logging: *logging
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging: *logging
    networks:
      - loki