version: "3.7"

networks:
  loki:

services:
  app_python:
    image: rkbekzat/moscow_time:latest
    container_name: app_python
    ports:
      - "8080:8080"
    logging: &logging
      driver: "json-file"
      options:
        tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 500M

  app_go:
    image: rkbekzat/weather:latest
    container_name: app_go
    ports:
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 500M

  loki:
    container_name: loki
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:3100/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ${PWD}/promtail/config.yml:/etc/promtail/config.yml:ro
    command: -config.file=etc/promtail/config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10 bash -c 'cat < /dev/null > /dev/tcp/localhost/9080' || exit 1" ]
      interval: 30s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana:/etc/grafana/provisioning
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:3000/api/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 500M

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - loki
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000" ]
      timeout: 10s
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./prometheus/config.yml:/etc/prometheus/config.yml
    command:
      [
        "--log.level=debug",
        "--config.file=/etc/prometheus/config.yml",
        "--query.lookback-delta=30s",
      ]
    deploy:
      resources:
        limits:
          memory: 500M